version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t sample-app .
      - docker tag 640168415754.dkr.ecr.ap-southeast-1.amazonaws.com/sample-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push :latest

artifacts:
  files:
    - '**/*'
